# Generated by Django 6.0.5 on 2026-05-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_delivery_cost', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='стоимость экспресс-доставки')),
                ('ordinary_delivery_cost', models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='стоимость обычной доставки')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='порог бесплатной доставки')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='индекс сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shopapp.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('delivery_type', models.CharField(choices=[('ordinary', 'Обычная доставка'), ('express', 'Экспресс-доставка')], default='ordinary', max_length=10, verbose_name='способ доставки')),
                ('payment_type', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счёта')], default='online', max_length=10, verbose_name='способ оплаты')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общая стоимость')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('paid', 'Оплачен'), ('payment_error', 'Ошибка оплаты')], default='created', max_length=15, verbose_name='статус')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='город')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('payment_error', models.CharField(blank=True, max_length=255, null=True, verbose_name='ошибка оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='индекс сортировки')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='рейтинг')),
                ('purchases_count', models.PositiveIntegerField(default=0, verbose_name='количество покупок')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shopapp.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='shopapp.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['sort_index', '-purchases_count'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена на момент покупки')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopapp.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='alt-текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='автор')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('rate', models.PositiveSmallIntegerField(default=5, verbose_name='оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shopapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена со скидкой')),
                ('date_from', models.DateField(verbose_name='дата начала')),
                ('date_to', models.DateField(verbose_name='дата окончания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shopapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='характеристика')),
                ('value', models.CharField(max_length=255, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shopapp.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
    ]
