# Generated by Django 6.0.5 on 2026-05-15 12:46

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_preview', 'pk'], 'verbose_name': 'изображение товара', 'verbose_name_plural': 'изображения товаров'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='основное изображение (preview)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.ImageField(upload_to=shopapp.models.product_image_upload_to, verbose_name='изображение'),
        ),
    ]
